---
version: "2.0"
services:
  storj-gateway:
    image: xdmaury/akash-storj:v0.0.1
    expose:
      - port: 7777
        to:
          - global: true
    env:
      - ACCESS_GRANT=<grant-key>
profiles:
  compute:
    storj-gateway:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        storj-gateway:
          denom: uakt
          amount: 1000
deployment:
  storj-gateway:
    dcloud:
      profile: storj-gateway
      count: 1
